

'use client';
import Link from "next/link";
import styles from "./page.module.css";
import { useState } from "react";
import 'bootstrap/dist/css/bootstrap.min.css';
import { FaShoppingCart } from "react-icons/fa";




export default function ProductsLayout({ children }) {

  const UI_ACTIVE_BUTTONS = {
    HOME: 'HOME',
    ABOUT: 'ABOUT',
    CONTACT: 'CONTACT',
    CART: 'CART',
  };


  const [isActiveBtn, setIsActiveBtn] = useState(UI_ACTIVE_BUTTONS.HOME);


  return (
    <>
      <html>
        <body>
          <header className={styles.layout}>


            <Link className={styles.logo} href="/"
              onClick={() => setIsActiveBtn(UI_ACTIVE_BUTTONS.HOME)}
            >
              <h1>HoldIt</h1>
              <p>climbing gear store</p>
            </Link>

            <Link href="/pages/about"
              style={{ color: isActiveBtn === UI_ACTIVE_BUTTONS.ABOUT ? 'red' : ' ' }}
              onClick={() => setIsActiveBtn(UI_ACTIVE_BUTTONS.ABOUT)}
            >About
            </Link>

            <Link href="/pages/contact"
              style={{ color: isActiveBtn === UI_ACTIVE_BUTTONS.CONTACT ? 'red' : ' ' }}
              onClick={() => setIsActiveBtn(UI_ACTIVE_BUTTONS.CONTACT)}
            >Contact
            </Link>


            <Link href="/pages/cart"
              style={{ color: isActiveBtn === UI_ACTIVE_BUTTONS.CART ? 'red' : ' ' }}
              onClick={() => setIsActiveBtn(UI_ACTIVE_BUTTONS.CART)}
            >
              <FaShoppingCart />
            </Link>


            {/* 
            <Link href="/products"
              style={{ color: isActiveBtn === UI_ACTIVE_BUTTONS.PRODUCTS_MANAGMENT ? 'red' : ' ' }}
              onClick={() => setIsActiveBtn(UI_ACTIVE_BUTTONS.PRODUCTS_MANAGMENT)}
            >Products Management
            </Link> */}

            {/* <Link href="/products/add">Add Product</Link> */}
          </header>
          {children}
        </body>
      </html >
    </>
  )
}
















// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }